#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION_FULL "2019.4.21f1_b76dac84db26"
#define UNITY_VERSION_FULL_NICE "2019.4.21f1 (b76dac84db26)"
#define UNITY_VERSION_BLD 12021164
#define UNITY_VERSION_DATE 1613616221
#define UNITY_VERSION_WIN "2019.4.21.12021164"
#define UNITY_VERSION_BRANCH "2019.4/staging"
